name: arxiv-rag-elk-env
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pandas=2.2.1
  - openpyxl=3.1.2       # required for Excel export
  - feedparser=6.0.11
  - tqdm=4.66.1          # optional: progress bars
  - requests             # for downloading PDFs
